### ISSUE TITLE
Use EmitDefaults: true for jsonpb.Marshaler in generated server code.

### ISSUE THREAD

**Issue by larrymyers** [twitchtv/twirp#103]
protoc-gen-twirp/generator.go#L1012

In generateServerJSONMethod the jsonpb.Marshaler instance should likely include `EmitDefaults: true` as an option.  While Go has a concept of zero values, javascript does not (i.e. the number `0` and `undefined` are very different things).

Let's say a proto Message struct in Go is:

```
type Hat struct {
  Name    string
  Size       int32
  IsFancy bool
}
```

Serializing this Hat instance with the twirp jsonpb.Marshaler does the following:

```
hat := Hat{Name: "", Size: 0}
```

JSON:

```
{}
```

Thoughts?

**Comment by larrymyers** [comment]
@spenczar If you want to slot this into the v6 release I'll happily provide a pull request with the code fix and documentation.

**Comment by ijhuang** [comment]
any chance this will make it into v6?

**Comment by marioizquierdo** [comment]
Some context and comments on this issue.

### Zero and Undefined is not the same

True. In many languages (specially in JavaScript) `0` and `undefined` are not the same thing, but that should not matter as long as you use an autogenerated client. For example, if a field type is a integer, the returned value from the client will always be an integer, never undefined. The network protocol is the one that doesn't differentiate between zero-values and undefined, with the goal of using as little bandwidth as possible. Autogenerated clients must de-serialize the code using the official json-pb mapping protocol: https://developers.google.com/protocol-buffers/docs/proto3#json.

If your service actually needs to differentiate between zero and undefined values, you should add a second boolean property in the Proto file (true if the value exists), or wrap the value with one of the [well known message types](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf) (message values can be undefined).

### Manually handling/debugging JSON requests

If you are manually parsing the JSON returned by a Twirp service, you probably find annoying having to handle all those undefined values. If you are making curl requests, you probably find annoying having to guess if the missing fields are zero-values or were not implemented yet. I hear you, this may be a real issue.

Being able to access the services with JSON is just *too convenient*, specially from JavaScript, where there's still not a clear easy-to-use alternative. 

### Twirp works with JSON, but is Protobuf at heart

Twirp by design allows Protobuf and JSON serialization ([docs/proto_and_json](https://twitchtv.github.io/twirp/docs/proto_and_json.html)), but JSON is meant to be a convenience. JSON serialization was not originally meant to be directly consumed by hand-written clients, but to be de-serialized with a schema autogenerated from the Proto file. With a schema, the serializer knows if a given undefined value is an integer and converts it into a zero-value `0`.

### Is EmitDefaults: true a good idea?

Looking back I personally think Twirp should always have use `EmitDefaults: true` as part of the protocol. Serialized JSON would need more bandwidth, but would better fit the goal of being convenient, leaving performance to the Protobuf serialization.

One option would be to change the protocol making `EmitDefaults: true` mandatory. I can't think of a case right now out of my head that would make old clients (that use `EmitDefaults: false`) backwards incompatible, but we have to explore that with much case (maybe `oneof` cases would break?). This change could also break other hand-written clients, although whatever is being done to interpret zeroes and non-existing values differently would be outside of the specification.

Another option is to allow using a flag like `emit_json_defaults` (PR https://github.com/twitchtv/twirp/pull/134) to help with backwards compatibility, but it would contradict the philosophy of keeping code generation as simple as possible. Twirp by design doesn't support code generation flags, that could add much complexity to the protocol. What if a service is generated with a flag and the clients with a different flag? What if the client is written in a different language and that flag is not supported in that language? Keeping the protocol simple and clear allows to easily implement Twirp in other languages and platforms. Serialization issues can be very hard to debug.

### Considering this for v6

There's no expected release data for v6 yet, but we believe it will happen in the next few months. That version got complicated because of streaming support in the protocol. But I agree, we should consider this for the next major release. Patience 😄. In the meantime, you can generate your code with the branch from the PR https://github.com/twitchtv/twirp/pull/134, if you do, please tell us if that is working as expected, it will help adding evidence to support this feature in the main branch. Cheers!

**Comment by marwan-at-work** [comment]
I'm running into this as well :) 

I think a better option than having emit_json_defaults as a param, is to give users a hook into creating the `jsonpb.Marshaler` struct since there are other options for json serialization such as "EnumsAsInts". 

And maybe even further, to have the hook take a `proto.Message` and return a `([]byte, error)` so that users can customize serialization based on their requirements. 

That said, keeping the protocol simple and less customizable is tempting from the maintainer's perspective. On the other hand, this would unblock a lot of users.  A compromise would be the protocol would only guarantee the default behavior and if a user wanted to pass a custom marshaler, it's their responsibility to ensure all of their clients are compatible.

**Comment by ilyar** [comment]
is there something new in this?

**Comment by dpolansky** [comment]
I agree with Mario's opinion above that `EmitDefaults: true` seems sensible for JSON in hindsight. JSON support exists in Twirp to aid with debugging, and seeing a JSON response such as `{}`  for an empty protobuf message can be confusing to many users.

However, this behavior will not change because it has significant potential to negatively impact Twirp's users. For instance, services using JSON in production would be impacted. A service that starts including default values in its JSON responses may experience a significant increase in the size of its response payloads, which may lead to unexpected changes in performance. Including this in a new major version was mentioned above, but this issue doesn't seem to outweigh the organizational cost that would be required by Twirp's users to safely perform a major version upgrade.

I agree that Twirp could make it possible for users change the behavior of the `jsonpb.Marshaler` in a way that is not supported by the protocol. For instance, an insertion point could be added to the generated code to allow other generators to inject a different value for the struct. However, I'm not yet convinced that this behavior is a blocker for users, since the protobuf "well-known types" provide a means of emitting default values on the wire (at the cost of not using the default protobuf types).

**Comment by marioizquierdo** [comment]
Here is a new attempt to solve this issue: #271

We can enable EmitDefaults by default on the upcoming v7, but still allow to disable it through the server constructor option `twirp.WithServerJSONSkipDefaults(true)` if required for full backwards compatibility.
