### ISSUE TITLE
Simultaneous response and error cannot be returned

### ISSUE THREAD

**Issue by peter-edge** [twitchtv/twirp#14]
The protocol as it stands only allows for either a response or an error to be returned. There are plenty of situations where something may want to return a valid value as well - think the `io.Writer` interface.

One way with HTTP to do this is to define response headers, something like 'rpc-error-code' and -'rpc-error-message', that carry this information in the headers. This became useful to use. Extending this paradigm to allow complex error returns is a topic for debate.

In terms of this protocol, you'd have to do some content negotation for backwards compatibility - think sending 'rpc-accepts-both-response-error' to denote you can handle this new form. We ran into this exact problem https://github.com/yarpc/yarpc-go/blob/dev/transport/http/constants.go#L79

Thoughts?

**Comment by cep21** [comment]
I wasn't a big fan of gRPC's use of errors for things like "not found".  It felt much more go-like for errors to mean something more serious than a 404.  I've found RPC style APIs that implement things like 404 or 409 Conflict easier to use if that was encoded in the message, and error was reserved for knowing my RPC call couldn't be processed.

**Comment by wora** [comment]
At Google, we manage over a thousand APIs, and we have seen this feature request a few times. But I don't think there is enough use case to justify a platform feature. You can easily embed an error payload in the response, or embed the response in the error details for special cases.

To support such feature, you need to update all client libraries and server libraries to support (response, error). This is extremely difficult to do in most programming languages. If you want to support OpenAPI, you will have hard time there. You also have to document extensively on how to handle partial errors.

The list goes on and on. It is very easy to implement the feature in Go, but you would leave a broken platform behind you for many years. A feature needs to be useful for 2% users in order to become a real platform feature. Otherwise, let applications handle it.
