### ISSUE TITLE
Make twirptest a public package instead of internal

### ISSUE THREAD

**Issue by iheanyi** [twitchtv/twirp#142]
Given that we are using using `twirptest` in various tests and whatnot (like here: https://github.com/twitchtv/twirp/blob/master/hooks/statsd/statsd_test.go#L23), I think it'd be beneficial to have the package public for individuals who want to write hooks for Twirp.

**Comment by dpolansky** [comment]
Thanks for helping us with Twirp.

We sincerely appreciate your contribution, but after discussing this internally, we believe that `twirptest` and its helpers should stay internal and unexported. The main intent of the `twirptest` package is for the project's own internal integration and regression testing, which sometimes depends on specific details of the way we setup the project.

However, we agree that the helpers provided by `twirptest` can be useful, as you demonstrated in the [twirp-opentracing](https://github.com/iheanyi/twirp-opentracing) repository. We think that it would be ideal to have a separate repository on Github, which could start out as just a direct copy of the test helpers in `twirptest`. With this approach, the package could evolve over time without adding additional maintenance burden on the Twirp project itself. What do you think? If you are interested in creating that repository, we would be happy to provide initial guidance and mention it on our own issues when appropriate.

**Comment by iheanyi** [comment]
@dpolansky Yeah, that makes sense to me! Thanks for the suggestion, I'll create the external package and then close this out once that is done, if that's okay with you all? Let me know what you think.

**Comment by iheanyi** [comment]
Hey @dpolansky, I've created a repo that extracted `twirptest` out here: https://github.com/iheanyi/twirptest

Let me know your thoughts and if there's anything in it that you think may need changing. Thanks again!

**Comment by dpolansky** [comment]
Hi @iheanyi,

Thank you for making a separate package for twirptest. I have some minor feedback:

1.) I did not expect to see the other subpackages from `/internal/twirptest` included in the repository (such as `no_package_name`, `multiple`, etc). These packages are intended to be used as tests for Twirp to ensure that it handles edge cases in `.proto` files appropriately. Could you elaborate on if you intended to include them in the repository and the purpose they would serve in a testing package?

2.) The `install_proto.bash` file aims to install `protoc` on different host types. You might consider directing users to the protoc documentation instead of taking on the responsibility of providing and maintaining an installer.

**Comment by iheanyi** [comment]
No problem @dpolansky:

1) Good catch, I originally just exported everything to get it working, but they won't serve any valid use-case within the tests. I'll get rid of those since the main focus of the usage is for the `Haberdasher` service.

2) That's also a good call. Will iterate on this and just make a generic `protoc` command for compiling the protobuf instead.

**Comment by spenczar** [comment]
Looks like this is resolved.
