### ISSUE TITLE
Decorate unmarshal error with field name

### ISSUE THREAD

**Issue by mfridman** [twitchtv/twirp#148]
Suppose a client decides to hand-write a JSON payload, but sends something unexpected. E.g., client sends string instead of a struct (read map).

The returned error indicates to the client:
1. internal error, 500  
2. the payload cannot be unmarshalled. 

```json
{
    "code": "internal",
    "msg": "failed to parse request json: json: cannot unmarshal string into Go value of type map[string]json.RawMessage",
    "meta": {
        "cause": "*somepb.wrappedError"
    }
}
```

But, it's not possible to determine _which_ field caused the error. For smaller payloads one could eye-ball, but this becomes much harder for larger objects.

Would it be feasible to return, within meta, the field that triggered the unmarshal error?

**Comment by mfridman** [comment]
This might be made possible if the upstream `jsonpb` added support for more error context.

https://github.com/golang/protobuf/issues/256
https://github.com/golang/protobuf/issues/266

Assuming these do get added, would it be reasonable to return within `meta` the key that caused the error?

**Comment by marioizquierdo** [comment]
I think this would also be useful for server error handling. An invalid request is a user-generated error, not a server error. It should be a 400, but Twirp was designed to be used with auto-generated clients in a microservices architecture, that should never send invalid payload... so it makes sense to be a 500 (InternalError). But in the real world people is putting Twirp services in the edge, and it is not cool if an attacker can send a load of invalid requests and trigger paging alerts. Adding meta for invalid requests may be a great way to allow the error hook to ignore server errors that are caused because of invalid payload.

**Comment by spenczar** [comment]
This sounds _really_ useful, yes. It also sounds hard to do without those upstream protobuf changes. I think if https://github.com/golang/protobuf/issues/266 lands, we should certainly do this.

**Comment by mfridman** [comment]
Going to swing back to this and see if this was fixed with the upstream changes in v2 as mentioned in https://github.com/golang/protobuf/pull/310
