### ISSUE TITLE
Updating context within method

### ISSUE THREAD

**Issue by seddonm1** [twitchtv/twirp#180]
Hi,
Is there a way to update the context within a service method? Or would that require modifying twirp to support a third result (and if so would this be a potential inclusion in v6)?

```golang
Method(ctx context.Context, req *package.RequestMessage) (ctx context.Context, *package.ResponseMessage, error)
```

Thanks

**Comment by spenczar** [comment]
We don't support this today Can you say more on why this would be useful?

**Comment by seddonm1** [comment]
I use the Server Hooks to perform logging. I use the context to pass additional metadata around with the request (like how you calculate TimingDuration in the statsd example). It would be nice to be able to add metadata from the individual methods responding to the request - primarily just for a richer logging story.

ps. twirp is excellent - good work 👍

**Comment by spenczar** [comment]
@seddonm1 One way to accomplish this today is through middleware and a mutating context value. For example:
```go
type ctxkey string
const reqMetaKey ctxkey = "request-meta"

func WithRequestMetadataTracking(ctx context.Context) context.Context {
  return context.WithValue(ctx, reqMetaKey, make(map[string]string))
}

func SetMeta(ctx context.Context, key, val string) {
  v, ok := ctx.Value(reqMetaKey).(map[string]string)
  if !ok {
    panic("request metadata context is not properly established, use WithRequestMetadataTracking")
  }
  v[key] = val
}

func GetMeta(ctx context.Context) map[string]string {
  v, ok := ctx.Value(reqMetaKey).(map[string]string)
  if !ok {
    panic("request metadata context is not properly established, use WithRequestMetadataTracking")
  }
  return v
}
```

You can call `WithRequestMetadataTracking` either as a hook at `RequestReceived`, or as HTTP middleware which wraps the Twirp server and gives an `http.Handler`. Either works. Then you can call `SetMeta` in your method, and `GetMeta` where you want to log.

Does this fill your need? I prefer this a bit because returning the context is sort of a strange signature.

**Comment by seddonm1** [comment]
Yes. This works correctly.
Sorry I have been switching languages too much.
