### ISSUE TITLE
Introduce hooks for custom validations

### ISSUE THREAD

**Issue by hexdigest** [twitchtv/twirp#184]
Hi,

I'm unable to find any hook that accepts unmarshalled request in order to perform some custom validation of the request. Typically tools that generate validators produce `func (r Request) Validate() error` method based on Request fields' inline tags.

Do you think it makes sense to introduce new hook like:
```go
// RequestUnmarshalled hook is called when a request has been unmarshalled into the
// destination struct
RequestUnmarshalled func(context.Context, interface{}) (context.Context, error)
```

Inside the hook we can check that passed `interface{}` argument implements `Validatable` interface and call the `Validate()` method if it does.

This hook will allow to perform basic validations on a framework level without spoiling the code of actual handlers. It may also be useful for something else for example for authentication if the auth credentials are passed as fields of the pb/json requests.

Should I make a PR for this?

**Comment by spenczar** [comment]
I agree that this helps with a few things that come up, like validation and auth. But I have a few concerns.

First, I think the `interface{}` type proves that the hook doesn't really decouple things very well. The auth/validation hooks need to know the request type to be able to actually do anything with the unmarshalled message. Instead of saying "you need to validate the request in all your handlers," this would seem to say "you need to modify the request types for all your handlers, and put these hooks in front." Is that really better? It seems merely different.

Second, can you say more about how validations "spoil the code of actual handlers?" I like having validation directly in the handlers, since it makes it clear what the expectations are per-method. Excess abstraction of server handlers has made for some of the nastiest, hardest-to-untangle bugs in my career, so I think we need a very good story there.

Third, I worry a lot about `RequestUnmarshalled` mutating the request shape. The absolute worst thing we could do is permit a stack of middleware that transforms the request. That can be very difficult to debug, and makes it too easy to build piles of abstraction. One option here is to do a deep copy after unmarshalling, but that's pretty expensive to do on every request.

**Comment by shouichi** [comment]
We generate validation/authentication "middlewares" that implements the service interface from proto. Then we chain those with the handwritten service implementation e.g., `rpc.Chain(validator, authenticator, server)`. This works very well for us.

The tools we use are:

- https://github.com/lyft/protoc-gen-star
- https://github.com/envoyproxy/protoc-gen-validate

Hope this helps.

**Comment by hexdigest** [comment]
Hi @spenczar !

Thanks for the quick response.

>  The auth/validation hooks need to know the request type to be able to actually do anything with the unmarshalled message. 

There's no need to know the exact type of the request. For example the [protoc-gen-validate](https://github.com/envoyproxy/protoc-gen-validate) mentioned by @shouichi generates `Validate() error` method so your hook should only define the interface to make a type assertion and perform the validation.

> Instead of saying "you need to validate the request in all your handlers," this would seem to say "you need to modify the request types for all your handlers, and put these hooks in front." Is that really better?

Let's continue with protoc-gen-validate which is my case actually. This tool generates a `Validate` method so technically you don't need to modify any types for all your handlers. What you need to modify is the .proto file and you already do it if you use such generators. And as I mentioned earlier since you have `Validatable` interface you need to put only one hook in front of all handlers.

> I like having validation directly in the handlers, since it makes it clear what the expectations are per-method.

You might like it but most of the people I talked to do not. It's way more convenient to see validations defined in .proto files that are shared between many people (backend, frontend, mobile developers, QA, tech writers and so on) rather then scattered somewhere in the code. Why do you need exactly same routine

```go
if v, ok := request.(Validatable); ok {
   if err := v.Validate(); err != nil {
     //handle error here
   }
}
```
in every handler while it can be done in the hook/middleware?

> I worry a lot about RequestUnmarshalled mutating the request shape.

It's hard to disagree with this but you don't obliged to mutate the request or build the piles of abstraction don't you? But if you decide to do this you have to have strong reasons for this.

**Comment by hexdigest** [comment]
Thanks for sharing your experience @shouichi 
I thought about generating middleware code but the thing is that I don't want to end up with exatly same piece of generated code for every method.

**Comment by hexdigest** [comment]
@shouichi @spenczar 

JFYI: I ended up writing a **twirp_validate** template for [GoWrap](https://github.com/hexdigest/gowrap) middleware generation tool.
