### ISSUE TITLE
Repeated fields in requests are not matched with models correctly

### ISSUE THREAD

**Issue by mikhail-eremin** [twitchtv/twirp#189]
Hi!
Have problem with connecting generated [twirp js client](https://github.com/thechriswalker/protoc-gen-twirp_js) with go twirp server. Everything works as expected beside repeated fields in requests

For example, if I have
```
message Request {
    repeated int64 ids = 1;
}
```
Generated golang model will have json annotation for ids field as following -`json:"ids,omitempty"`
Generated JS client(protoc-gen-twirp_js) will send that field in json as "idsList". Those fields are not matched at server-side, as a result I always have empty ids field at server-side

I tried same case with grpc + grpc web, where everything works same way (I mean - repeated fields are also postfixed with "List" in js requests, and model generated from proto also have json annotation without "List" postfix), but fields are matched and work as expected.

I am not sure if that issue should be in protoc-gen-twirp_js repository, I put it here because grpc web js client works with fields same way as protoc-gen-twirp_js, so I think it should be fixed at server side

Thank you

**Comment by spenczar** [comment]
Hi - I think this is an issue in the generator that is producing your javascript message types - probably something like `protoc-gen-js`.

Changing the server side would be wrong because using the name `idsList` is incorrect. This is governed by the Protobuf spec for JSON encoding, https://developers.google.com/protocol-buffers/docs/proto3#json.
