### ISSUE TITLE
advice on other langs

### ISSUE THREAD

**Issue by rileytg** [twitchtv/twirp#19]
i’m interested in ruby and java support (maybe php too). any advice along these lines?

**Comment by gaffneyc** [comment]
I've started on a generator for Ruby: https://github.com/gaffneyc/protoc-gen-twirp_ruby

It's functional enough to generate a working client based on the haberdasher demo. I would appreciate any feedback or pull requests. I'm prototyping a service with Twirp and will need it to talk the service from our main Rails app on Dead Man's Snitch. If the prototype is successful I'll keep working on it and productionatize it as I go.

**Comment by spenczar** [comment]
Glad to hear it (and amazed at how quickly you got that out, @gaffneyc, holy smokes)!

I'd love to help. I think generating a client should be simple. Here's what I suggest:
1. Write a protobuf spec for a service. Make sure it has multiple methods, a few different message types - you want to cover some corner cases.
2. Generate Twirp server code and run a Twirp server on localhost so you have something to test against.
3. Write a client in the language you're targeting by hand. Try to make it feel nice to use, good and idiomatic.
4. Copy `protoc-gen-twirp`, give it a language-specific name like `protoc-gen-twirp_java` or whatever, and hack at your copy until it generates an output that looks just like your hand-written client.
5. Make sure your generated client works by testing it against the running Go server. You need to handle routing and serialization, and also error responses.
6. To make sure you handle errors correctly, run your client against `clientcompat`, which is a package in the Twirp repo that has a kind of framework for stressing a client implementation.

Your generated client should speak protobuf. It doesn't need to be able to speak JSON, really.

Some of the danger spots to watch out for:
 - Do you deserialize errors correctly?
 - Do you handle things correctly if there is no twirp server running at the address requested, and you just get (say) a generic nginx text error?
 - Does your generator correctly handle message definitions that are imported from other protobuf files?

As always, feel free to ping me directly if you need any help. The gophers slack is a good place to do this, or here.

**Comment by gedw99** [comment]
Dart team tend to use JSON RPC.
https://github.com/dart-lang/json_rpc_2

**Comment by gaffneyc** [comment]
@spenczar Thanks! The python generator was a really good reference that made it a lot easier. I had to reinvent a few wheels since the `gen` package is internal. In this case it was a good thing since it gave me the excuse to learn Go's templating.

**Comment by daroot** [comment]
Would there be any interest in PRs for server-side support to the non-go generators?

It seems to me that it'd be nice to be able to write  Twirp compatible server in, say, Python or Ruby.

**Comment by fajran** [comment]
I am interested in adding Java support. I have a quick prototype of the client code (using JAX-RS lib) based on the python generator https://github.com/fajran/twirp/tree/java-jaxrs

**Comment by spenczar** [comment]
@daroot, Yes! Definitely interested in server support.

I think the bar for including a server generator in this repo should be exceptionally high. I'd prefer to see some experimentation in external repositories, and then we can move them into this repo if they seem really solid, reliable in production, and well-supported. But while you're working on any server implementations, please don't hesitate to ping me for input and feedback to make sure you're following all the corner cases I can think of.

@fajran nice! excited to see where it goes - java is one of the most important languages for us to target.

**Comment by marioizquierdo** [comment]
I think a good reference on what to look for on a client generated for another language is the [doProtoRequest](https://github.com/twitchtv/twirp/blob/dff337b186d4ea1ada1d1e54ef422fdbcfa3113d/example/service.twirp.go#L592) method used by generated Go Clients. Even if you don't know much about go, this shows all the things that the client should care about when handling a Twirp request:

What this is doing is:
  1. Serialize request body.
  2. Make a POST request with `Content-Type` and `Twirp-Version` headers.
  3. Check if the response status code is 200, otherwise [handle error](https://github.com/twitchtv/twirp/blob/dff337b186d4ea1ada1d1e54ef422fdbcfa3113d/example/service.twirp.go#L470):
     * if it is a 3xx, return a Twirp Internal error (redirects not allowed on POST requests).
     * if it is a 4xx or 5xx, and the body is a valid serialized Twirp error, then build a Twirp error
     * if it is a 4xx or 5xx, but not a valid Twirp error, then assume is an error from some middle-proxy. There's a [mapping from http codes to twirp errors](https://github.com/twitchtv/twirp/blob/dff337b186d4ea1ada1d1e54ef422fdbcfa3113d/example/service.twirp.go#L510) that can be used.
  4. De-serialize response.

Somethings that the Go client does that may be only relevant to the Go language (you may handle this differently in other languages):
 * Errors are returned as regular values that are instances of `twirp.Error` that implements the `error` interface. In other languages like Java and Ruby you may want to throw exceptions. However, you should think about returning Twirp errors as part of the response object because some errors are used for business logic (e.g. `InvalidArgument`), and only throwing exceptions for "client errors" (internal errors produced in the client, like when de-serializing the response).
 * The `cxt context.Context` parameter is used to be able to cancel on-going requests, and also to allow configuring HTTP client roundtrippers. This may work differently in your Language (maybe through the request object).
 * The client is instantiated accepting a host address and a `HTTPClient` interface. This is because Twirp should only be used for routing and serialization, leaving the HTTP specifics to another networking library. Every language has different conventions about the way to handle HTTP requests. Ideally Twirp would work with any of the most common HTTP libraries on your language.
 * Most of the client code is auto-generated from the Protobuf service definition. However it may be useful to define a static `twirp` or `twirpcli` package to import common types like [twirp.Error](https://github.com/twitchtv/twirp/blob/dff337b186d4ea1ada1d1e54ef422fdbcfa3113d/errors.go) and certain constants. Only stable parts of the Twirp protocol should be extracted to its own library. The generated code should have as few dependencies as possible.

**Comment by spenczar** [comment]
I'm going to close this issue, as there isn't really an action item here. We may come back to scoop this stuff up when writing documentation.

For now, I'd encourage anyone who has written a client to take a look at #61 - I'd like to list y'all on the README.
