### ISSUE TITLE
Add CORS headers to OPTIONS request to the golang net/http twirp server

### ISSUE THREAD

**Issue by mr-rick** [twitchtv/twirp#210]
I know that the golang twirp net/http server only accepts POST requests.  However I was hoping there was a way to intercept the OPTIONS request to inject CORS response headers for browsers that want to connect to twirp using http1.1 and REST

**Comment by spenczar** [comment]
Could you say more about why this needs to be baked into Twirp?

Handling preflight OPTIONS requests should work with any existing library for CORS, since Twirp servers aren't special, they're just `http.Handler`s. For example, using [github.com/rs/cors](https://github.com/rs/cors) looks like this:
```go
package main

import (
	"net/http"

	"github.com/rs/cors"
	"github.com/twitchtv/twirp/example"
)

func main() {
	// Make your Twirp application and server:
	twirpServer := example.NewHaberdasherServer(nil, nil)

	// Make a CORS wrapper:
	corsWrapper := cors.New(cors.Options{
		AllowedOrigins: []string{"haberdasher.org", "haberdasher.gov"},
		AllowedMethods: []string{"POST"},
		AllowedHeaders: []string{"Content-Type"},
	})

	// Do the wrapping, and serve it:
	handler := corsWrapper.Handler(twirpServer)
	http.ListenAndServe(":8080", handler)
}
```

Is this not working?

**Comment by dpolansky** [comment]
I am closing this issue for now. Feel free to comment if this needs to be discussed further.

**Comment by DGollings** [comment]
Although I can appreciate you want to keep your code lightweight it doesn't mean the documentation needs to be as well. :)

Found this because I ran into the same issue, maybe add the above CORS options example + 
setting
```
func (h *myServer) MyRPC(ctx context.Context, req *pb.Req) (*pb.Resp, error) {
  err := twirp.SetHTTPResponseHeader(ctx, "Access-Control-Allow-Origin", "*")
  return &pb.Resp{}, nil
}
```
in all routes that need to respond to CORS preflight requests to the https://twitchtv.github.io/twirp/docs/headers.html page? 

Separately, is it possible to handle CORS globally instead of per route?
