### ISSUE TITLE
Add a callback that accepts input arguments and results

### ISSUE THREAD

**Issue by Cyberax** [twitchtv/twirp#212]
We'd like to log request and responses from Twirp services and also to validate the input parameters using https://github.com/envoyproxy/protoc-gen-validate . Right now this is not possible, because the callbacks have no access to deserialized request body.

My proposal it to add ServerHooksExtended that would have two additional functions: `RequestUnmarshalled(context.Context, interface{}) error` and `ResponseReady(context.Context, interface{}) error`.

**Comment by spenczar** [comment]
I really worry about doing this, for two main reasons:

 - *Loose typing:* using `interface{}` means that callers need to do type assertions to get any value out of this. But what type do they assert to? Asserting to the concrete message struct types is clearly not practical - at that point, just insert the code into each method. Asserting to an interface only works if you are running _additional_ generators to attach methods to the generated structs, like with `protoc-gen-validate`. At that point, why rely on the interface though - why not write another generator?
 - *Implies either deep copies, or req/resp mutability*: There's no way out of this, and both options are bad. Either we're doing a deep copy of the request/response object for each hook in the chain, or we're passing around a reference to mutable memory. I don't like the deep copy because it is expensive (mostly in terms of memory pressure - it's a lot of very temporary allocation) and requires a lot of reflection. I don't like mutability because it makes hooks too powerful, turning them into mutating middleware which is a source of bugs which are very difficult to understand.

Code generation seems like a better path, here. It's not hard to write a code generator, but maybe we should make it even easier - it should be trivial to write as `protoc` plugin that wraps your twirp server, adding pre- or post-method call behavior. This would definitely be type-safe (since you'd generate the "handlers" by sticking them in every generated method). It would side towards mutability, but in a way that should be much more transparent.

This sounds easy to me today, but I'm very biased! I am sure there is room for a better tool to make Twirp "extensions" of some kind - maybe a generator generator?

**Comment by Cyberax** [comment]
With protoc-gen-validate I can simply cast objects to Validate interface and then call its methods.  Ditto for logging. This is a low-effort way if hooks are added.

A configurable generator sounds interesting, but I don't think it would work in practice. It would quickly become a meta-language, so that just writing a plugin for protoc would be easier than mastering it.

Another possible solution is to write a generator that would create a proxy wrapper that would call my proposed hooks. I guess I'll go this route if my request is rejected.

It would also be nice to be able to augment the returned errors in ClientHooks.Error, twirp.Error is immutable so there's no problem with allowing to return a new copy of it. The major use-case is to be able to attach tracing metadata from the HTTP response to the returned error.

**Comment by spenczar** [comment]
> Another possible solution is to write a generator that would create a proxy wrapper that would call my proposed hooks. I guess I'll go this route if my request is rejected.

I would really like to encourage writing generators, yeah. This seems like a perfect example of where I think they would be useful - I think they can be a more-powerful route than hooks.

I can help by writing the simple wrapper generator and pushing it to a repo if you like, to at least serve as a demonstration. It could be a good reference to point people towards, to show that writing a generator is surprisingly simple.

**Comment by Cyberax** [comment]
Writing a code generator was indeed not a big deal: https://github.com/aurorasolar/go-dd-service-base/blob/master/twirpwrap/templater.go
