### ISSUE TITLE
Add service name and method to error meta

### ISSUE THREAD

**Issue by vektah** [twitchtv/twirp#215]
For bugtracking and aggregation purposes we would like to put the service name and method called client side into the error meta. 

This turns out to be a little tricky, Does anyone have thoughts on how this can be done?

Possible changes that could be made to twirp to make this possible:

### Solution 1: Add ability to return error from client hooks

```go
hooks := &twirp.ClientHooks{
	Error: func(ctx context.Context, e twirp.Error) {
		if sn, ok := twirp.ServiceName(ctx); ok {
			e = e.WithMeta("twirp_service_name", sn)
		}
		if sn, ok := twirp.MethodName(ctx); ok {
			e = e.WithMeta("twirp_method_name", sn)
		}

		return e // !!! we cant return from this hook with new error
	},
}
```

### Solution 2: Add a SetMeta method to Error

This would allow us to easily mutate the existing error, but this feels a little wrong. I cant see any concurrency issues but I dont know the codebase very well.

```go
hooks := &twirp.ClientHooks{
	Error: func(ctx context.Context, e twirp.Error) {
		if sn, ok := twirp.ServiceName(ctx); ok {
			e.SetMeta("twirp_service_name", sn)
		}
		if sn, ok := twirp.MethodName(ctx); ok {
			e.SetMeta("twirp_method_name", sn)
		}
	},
}
````

### Solution 3:  Write it out in the generated code

I dont really like the look of this, its pretty gross as people who dont use would be allocating these maps on errors. But errors are pretty rare and its likely meta is sent to their bugtracking. Could end up helping someone else out :man_shrugging: 

```go
func (c *compatServiceJSONClient) Method(ctx context.Context, in *Req) (*Resp, error) {
	ctx = ctxsetters.WithPackageName(ctx, "twirp.clientcompat")
	ctx = ctxsetters.WithServiceName(ctx, "CompatService")
	ctx = ctxsetters.WithMethodName(ctx, "Method")
	out := new(Resp)
	err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		twerr = twerr.SetMeta("twirp_service_name", "CompatService")
		twerr = twerr.SetMeta("twirp_service_name", "Method")
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}
```

Thoughts? I'm happy to PR if we can decide on a way forward.

**Comment by spenczar** [comment]
This is a tough one. Solutions 1 and 2 are unappealing to me - I really don't like making hooks capable of mutating errors, since that sort of tool can result in such confusing behavior. It can make it much, much harder to debug something if not done extremely carefully. Middleware that mutates errors just seems so dangerous.

Solution 3 is more tolerable. The map allocation is dirt cheap. The hardest part is probably the naming - we'd want something that doesn't ever collide with existing usage. It also leads to the immediate question "why not always include this from the server side?"

One remaining solution - you could write a new client generator. It takes a `.proto` file in and generates this function:
```go
func AnnotateErrors(client example.Haberdasher) example.Haberdasher {
	return annotatedErrorHaberdasherClient{base: client}
}

type annotatedErrorHaberdasherClient struct {
	base example.Haberdasher
}

// this needs to be repeated for every method on the service
func (h annotatedErrorHaberdasherClient) MakeHat(ctx context.Context, req *example.Size) (*example.Hat, error) {
	resp, err := h.base.MakeHat(ctx, req)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		twerr = twerr.SetMeta("twirp_service_name", "CompatService")
		twerr = twerr.SetMeta("twirp_service_name", "Method")
		return nil, twerr
	}
	return resp, nil
}
```

You'd emit this generated code to a file of your choosing. You'd generate it through a `protoc` plugin, so you do something like 
```bash
protoc --go_out=. --twirp_out=. --twirp_error_annotator_out=. svc.proto
```
---

However, I'm not sure I understand why twirp error metadata, inserted client-side, are the best way for you to accomplish what you want. This is inside the client, so it already has access to the `context.Context` variable with service and method name attached. Why not access the context for bugtracking and aggregation?

**Comment by vektah** [comment]
> It can make it much, much harder to debug something if not done extremely carefully. Middleware that mutates errors just seems so dangerous.

I dont think this is complicated or dangerous. I doubt you would ever see an app with more than one error hook, its there to capture whatever is needed as close to the error as possible - isnt it? What risk do you see here? We do something [really similar server side in gqlgen](https://gqlgen.com/reference/errors/#the-error-presenter)

> One remaining solution - you could write a new client generator. It takes a .proto file in and generates this function:

Yeah we thought about this too, then saw client hooks had landed and we can almost get what we want without generating thousands of lines of facades.

> This is inside the client, so it already has access to the context.Context

The client context is never exposed to the user, except in the error hook.

I think the hangup is that the twirp client shouldn't be responsible for doing its own bug tracking, the caller should - if and only if the failure is unexpected. But we do want as much context from the call as possible.

For example
-  looking up and not finding a random user is a twirp error, but not worthy of sending to the bugtracker.
-  looking up the logged in user and not finding it, thats probably a bug.

With the current hook we are forced to send the error off to the bugtracker without knowing which context we are in, or make the caller responsible for tracking each one individually, with hand written custom wrapping (very error prone).

With solution 1 we can rely on our bugtrackers wrapping method (we use bugsnag, errors.New captures traces) to wrap the outgoing error, capture a stacktrace and add whatever information we feel is relevant from context.

**Comment by spenczar** [comment]
> I dont think this is complicated or dangerous. I doubt you would ever see an app with more than one error hook, its there to capture whatever is needed as close to the error as possible - isnt it? What risk do you see here?

Today's error hooks can't change the error. They're intended to be used for error reporting, logging that sort of thing (actually, exactly the use cases you're describing).

Once hooks can change the error, they open the door to many more confusing cases. You could get `nil, nil` results from calling a client method, which is almost certain to crash. You could have errors which are rewritten quietly, so you see an error in server logs but can't find the corresponding error in client logs. You can say "well, don't misuse them" - but that's the point, they're a dangerous tool that needs warnings attached. As a rule, the design principle for Twirp is to keep things consistent, standard, and safe for broad use without warnings like that.

> Yeah we thought about this too, then saw client hooks had landed and we can almost get what we want without generating thousands of lines of facades.

Can you say more about why the line count of generated code affects you?

I know generating code is a little unconventional, but I think it's an underrated option, especially in a language like Go which is so simple to generate. 

> With the current hook we are forced to send the error off to the bugtracker without knowing which context we are in, or make the caller responsible for tracking each one individually, with hand written custom wrapping (very error prone).

I don't understand this, maybe because I don't know what you mean by "without knowing which context we are in." Why can't you implement bugtracking logic inside an `Error` hook, looking things up from the `context.Context` you have on hand?

**Comment by vektah** [comment]
We cant handle the error inside the hook, becuase the client still returns it. Heres a great description of the issue https://dave.cheney.net/tag/error-handling#handle-errors-once.

A real error handler is final, the error is logged and not passed up the call chain any further, the code flow altered to deal with the error. With the current hook the error is still passed to the caller. They can still log it, they still need to adjust their code flow.

Ill reword the example from above to illustrate:
 - calling GetUserById(123) for a random user from a get param and getting a twirp not found error. This should be a http not found sent back to the user, the bug tracker should never now.
 - calling GetUserById(me) for the logged in user should error and be sent to the bug tracker. There is a database inconsistency that needs to be addressed. How can a logged in user not exist?

This is what I meant by *context*, its the callers job to handle errors because they know the *context* of the call. Is it critical? Are some failures expected? All the client should do is make as much info available to the caller as possible.

**Comment by spenczar** [comment]
Okay, I think I have a good picture of how you want to structure your code, and why the current thing doesn't feel adequate.

I still don't think the right fix is to add to the metadata structure on the error. That thing has a funny type - it's a `map[string]string` - which is 100% motivated by the goal of making it simple to serialize and deserialize.

One thing that remains strange to me is that the caller necessarily has the context already, don't they? They know what service and method they are calling. They also know whether it's a random user from a get param or whatever. Error hooks don't know the full call stack, and adding it all there seems a bit backwards, since the callsite is always actually authoritative.

I can see how error hooks would help you identify what method and service name were called. But in your example, how would your proposal tell the difference between whether a user ID came from a query parameter or a cookie?

**Comment by vektah** [comment]
> One thing that remains strange to me is that the caller necessarily has the context already, don't they? They know what service and method they are calling. They also know whether it's a random user from a get param or whatever. 
They do, but we use twirp for our internal apis so this requires manually wrapping every client call with the method name and service to figure out what failed. Thats not a good tradeoff to me.

> Error hooks don't know the full call stack, and adding it all there seems a bit backwards, since the callsite is always actually authoritative.

I dont follow, they have a more complete stack that contains the line the caller called the client.

> I can see how error hooks would help you identify what method and service name were called. But in your example, how would your proposal tell the difference between whether a user ID came from a query parameter or a cookie?

The caller just does it, they already know. If you are ok with a failure (eg query param) for example in a handler you could either:
```go
u, err := userService.GetUser(123)
if err != nil {
   // Safely handled! Dont send to bugtracker! 
   w.Write(http.StatusNotFound)
   return
}
// do something with u
```

If its exceptional and cant be recovered
```go
u, err := userService.GetUser(123)
if err != nil {
   panic(err)
}
// do something with u
```

This isnt a great example because when panicing the stacktrace is complete enough to know which call failed. In our real use case (graphql bff) errors get returned rather than panicing on the spot.

**Comment by marioizquierdo** [comment]
Solution 5: **Add metadata manually as needed**. A brute-force, grunt approach. That is, wrapping the error or adding metadata after every call to the client. For example:

```go
// Logged in user
u, twerr := twirpClient.GetUser(mySvc.GetUserRequest{UserId: loggedUserID})
if twerr != nil {
   // wrap error for our generic error reporter
   return errorshelper.InternalWith(twerr).
       WithProp("service", "users").WithProp("method", "GetUser")
}

// Find user by id
u, twerr := twirpClient.GetUser(mySvc.GetUserRequest{UserId: userID})
if twerr != nil {
    if twerr.Code() == twirp.NotFound {
      return errorshelper.HTTPNotFound("not found with user ID" + userID)
    } else {
         // wrap error for our generic error reporter
         return errorshelper.InternalWith(twerr).
             WithProp("service", "users").WithProp("method", "GetUser")
    }
}
```

This is repetitive, but not an uncommon style in Golang. As it is not uncommon to automate this with code generation if it is repeated too much (as suggested by Spencer in Solution 4). This is the same as when using generic JSON clients; the errors also need to be annotated somehow because Golang doesn't provide stacktraces.

**Comment by marioizquierdo** [comment]
Solution 6: **Using a twirp helper to annotate client errors**.
The twirp package could provide a helper function to allow annotating data into the error from the hook. Adding extra data, or simply adding the context into the error. For example:

```go
hooks := &twirp.ClientHooks{
  Error: func(ctx context.Context, twerr twirp.Error) {
      twirp.SetContext(twerr, ctx)
  },
}
```

This is different than mutating the error, because nothing in the original error is changed, and nothing is going to be sent over the wire that needs to be de-serialized later; the error's Code, Msg and Meta are the same as before.

Later, another helper like `twirp.GetContext(twerr)` would allow to extract the context, so you can get the service name and method form the error handler, or any extra data that you wanted to add in the hook.

**Comment by marioizquierdo** [comment]
Let's recap. It could be nice to have client errors with useful data like service name and method, or stack traces, so it can be easily extracted later during error reporting.

Since Twirp errors already have metadata, one idea would be to include service and method on the error metadata.

---

Let's review the proposed solutions:

Solution 1: **Allow to return errors from client hooks**
This would be a breaking change, and those are very difficult to get implemented in Twirp. And that would allow to mutate the error which goes directly against Twirp design principles.

Solution 2: **Add a SetMeta method to Error**
Same thing, it would be a breaking change and allow to mutate errors.

Solution 3: **Add the metadata by editing the generated code**.
Sure, if this a hack that works for you, but you know next time the client is re-generated those changes will disappear.

Solution 4: **Generate a wrapper to annotate errors**.
Like Spencer suggested in his answer, a common way to deal with this issue is to use code generation to wrap your Twirp client with something that wraps all the returned errors. You can add metadata in that wrapper, or you can return a different error type, that returns the original in a `Cause`.

Solution 5: **Wrap and/or add metadata manually as needed**.
Handle every case manually as needed.

Solution 6: **A new a twirp helper to annotate client errors with data**.
Instead of mutating the error metadata, a helper could be used to add more data in the client side. The easiest way I can think of is by adding the context into the error.


---

I don't think Solutions 1 and 2 will be addressed because the way Twirp principles of design.
Solutions 3, 4 and 5 are things you can do in your side to address the issue if Twirp doesn't change its API.
Solution 6 would be very easy to implement, adding two new helpers with some documentation.
