### ISSUE TITLE
Proposal: allow ResponsePrepared to return an error

### ISSUE THREAD

**Issue by mfridman** [twitchtv/twirp#219]
This is a non-backwards compatible proposal.

The proposal is to change the signature of the `ResponsePrepared` hook to return an `error`. So the hook would be:

    ResponsePrepared func(context.Context) (context.Context, error)

Having a hook that returns an error __before__ writing back to the client would enable for interesting use-cases.

E.g., in the `RequestReceived` you inject a context `checked=false`. Each method is explicitly required to set the context `checked=true`. Then in the `ResponsePrepared` one could grab the context and check if the bit has been flipped.

Say a developer implemented a new method, but forgot to do this step, you can catch this in e2e tests or during development because the method always returns an error. In other words, this forces a developer to think about explicitly flipping a bit in the method implementation.

This is a contrived example, but it showcases a potential use-case for `ResponsePrepared` to return an error.

Curious, was there a reason for `ResponsePrepared` to **not** return an error?

**Comment by dpolansky** [comment]
Apologies for the extremely late reply.

It is my understanding of Twirp's design goals that it was intentional to not provide mechanisms like this, specifically mechanisms that alter the control flow of the program. The goal of the hooks is to allow for instrumentation and observability, and to not allow for hooks to result in confusing program behavior. As you mention, it could allow for interesting and more powerful use cases, but hooks were not intended for this.

**Comment by mfridman** [comment]
Ye that makes sense. Upon reflection this might be the right design.

No worries, it's an open source project and y'all doing your best to support it.
