### ISSUE TITLE
Deprecated jsonpb package; customizing json encoder

### ISSUE THREAD

**Issue by titpetric** [twitchtv/twirp#253]
It seems the golang/protobuf/jsonpb package is deprecated.

- https://godoc.org/google.golang.org/protobuf/encoding/protojson is the recommended replacement

**Comment by titpetric** [comment]
Actually, it seems most (if not all) of my issues could be solved by using encoding/json as the encoder. It would be great if I could customize/override it instead of the protojson encoding.

I want the types in .proto, structs and json encoded payload to match, as I’m also sourcing the proto payloads to generate typescript definitions. Int64 should become number, and not a string, but all returned int64, []int64 are coalesced to a string type. While it may be fine for uint64 (since nodejs can’t handle unsigned ints nicely), it’s rubbing me the wrong way for int64.

**Comment by titpetric** [comment]
I'm probably going *directly to hell* for this hack, but I created an internal jsonpb package, and I'm rewriting the import name to it in the various *.twirp.go files; all the protobuf generated structs have `json` tags on the fields, and I'm not running into any naming issues for which `OrigName` existed in the jsonpb.Marshaler;

~~~go
package jsonpb

import (
        "encoding/json"
        "io"

        jpb "github.com/golang/protobuf/jsonpb"
)

type Unmarshaler = jpb.Unmarshaler

type Marshaler struct {
        OrigName bool
}

func (*Marshaler) Marshal(w io.Writer, src interface{}) error {
        return json.NewEncoder(w).Encode(src)
}
~~~

I'm not particularly sure where `OrigName` comes into effect. If I use `user_id` in the .proto files, this is the snippet that's generated with protobufs for that particular field:

~~~go
UserId   int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
~~~

The `json` tag here seems to match the protobuf name, which only leads me to believe that the jsonpb OrigName (which gets rewritten to protojson `UseProtoNames`), actually has the same behaviour as `encoding/json`. In conclusion, I can now use `number` and `number[]` in typescript files, without patching JSON.parse behaviour to cast back to numerics.

Now, I'm mostly going to hell since patching this isn't sustainable in the long term. One of the main reasons why I'm continuing to use Twirp is the simplicity and code generator with .proto files as the source; What I seem to be suggesting here is implementing a `Codec` interface, like [it exists in grpc package](https://godoc.org/google.golang.org/grpc#Codec). Hopefully this isn't a non-starter.

**Comment by spenczar** [comment]
How would you propose changing the [Twirp specification](https://github.com/twitchtv/twirp/blob/master/docs/spec_v5.md) to accomodate this? Today, Twirp says that JSON payloads should be encoded following the canonical, official Protobuf JSON mapping rules (https://developers.google.com/protocol-buffers/docs/proto3#json). Using `encoding/json` will lead to different results. I think that supporting alternative codecs sounds really hard - how does the server communicate the codecs it has available to the client, and how do we do this with a cross-language design? If the result is complex, I think it would be a step backwards for Twirp.

`int64` is encoded as a string because Javascript Numbers only have 53 bits of precision. You can't put fit a 64 bit integer into a Javascript number. If you don't need 64 bits of precision and the string bothers you, then int32 is the right type to use.

If you're having trouble decoding the jsonpb-encoded payloads, I think that sounds like a bug in the Protobuf JSON implementation in whatever language you're working with. https://github.com/stephenh/ts-proto looks like a TypeScript generator which handles the canonical JSON form correctly.

**Comment by titpetric** [comment]
>  Javascript Numbers only have 53 bits of precision.

I have finally found the ultimate reason why I prefer PHP.
