### ISSUE TITLE
Go package naming consistency

### ISSUE THREAD

**Issue by skolodyazhnyy** [twitchtv/twirp#255]
Hey,

I'm trying out twirp to compliment my GRPC server, but when I added `twirp_out` to protoc I got this error:

```
error:files have conflicting go_package settings, must be the same: "service1" and "service2"
```

It seems twirp enforces use of exactly same go package in all proto files, which is different from go and grpc code generators. I wonder if it's make sense and possible to remove this check so I can generate everything in one go:

```
protoc -I proto \
  --go_out=pkg      --go_opt=paths=source_relative \
  --go-grpc_out=pkg --go-grpc_opt=paths=source_relative \
  --go-http_out=pkg --go-http_opt=paths=source_relative \
  --twirp_out=pkg   --twirp_opt=paths=source_relative \
  proto/service1/service1.proto \
  proto/service2/service2.proto \
  proto/service3/service3.proto \
  proto/service4/service4.proto \
  proto/service5/service5.proto \
  proto/service6/service6.proto
```

Instead of same command repeated 6 times.

go and grpc code generators have no problem processing files with different go_package option, they put them in different folders and everything seems to work just fine.

**Comment by spenczar** [comment]
Interesting. The behavior in [`github.com/golang/protobuf/protoc-gen-go`](https://github.com/golang/protobuf/blob/d04d7b157bb510b1e0c10132224b616ac0e26b17/protoc-gen-go/generator/generator.go#L683-L691) is consistent with protoc-gen-twirp, which is why it was written this way: 
```go
	// Check that all files have a consistent package name and import path.
	for _, f := range g.genFiles[1:] {
		if a, b := g.genFiles[0].importPath, f.importPath; a != b {
			g.Fail(fmt.Sprintf("inconsistent package import paths: %v, %v", a, b))
		}
		if a, b := g.genFiles[0].packageName, f.packageName; a != b {
			g.Fail(fmt.Sprintf("inconsistent package names: %v, %v", a, b))
		}
	}
```

(well, also because `protoc-gen-twirp` predates the ability to set a fully-specified import path for `option go_package`; when the value is just a plain string, it's ambiguous what to do).

But the new behavior in [`google.golang.org/protobuf/cmd/protoc-gen-go`](https://github.com/protocolbuffers/protobuf-go/blob/5d63473da8fbf1e1008e1e636b097f581f825f0d/compiler/protogen/protogen.go#L361-L379) has a less-restrictive constraint:
```go
	// Consistency check: Every file with the same Go import path should have
	// the same Go package name.
	packageFiles := make(map[GoImportPath][]string)
	for filename, importPath := range importPaths {
		if _, ok := packageNames[filename]; !ok {
			// Skip files mentioned in a M<file>=<import_path> parameter
			// but which do not appear in the CodeGeneratorRequest.
			continue
		}
		packageFiles[importPath] = append(packageFiles[importPath], filename)
	}
	for importPath, filenames := range packageFiles {
		for i := 1; i < len(filenames); i++ {
			if a, b := packageNames[filenames[0]], packageNames[filenames[i]]; a != b {
				return nil, fmt.Errorf("Go package %v has inconsistent names %v (%v) and %v (%v)",
					importPath, a, filenames[0], b, filenames[i])
			}
		}
	}
```

Permitting multiple import paths in one run is trickier than you might imagine. There's [some bookkeeping](https://github.com/twitchtv/twirp/blob/master/protoc-gen-twirp/generator.go#L231-L234) in the code generator to make sure we generate helper functions just once. Changing that to a map of import paths is, of course, totally doable, it's just the first stumbling point that comes to mind. There may be more.

The point is, we can't just remove the error; there's a bit more refactoring required to support this. I think it makes sense that the Google protobuf folks did that only in their rewrite from github.com/golang/protobuf to google.golang.org/protobuf. This issue really raises a broader question: should `protoc-gen-twirp` switch to using [`google.golang.org/protobuf/compiler/protogen`](https://godoc.org/google.golang.org/protobuf/compiler/protogen)? That might help ensure compatibility, and it would be nice to be able to use stuff like [`protogen.QualifiedGoIdent`](https://godoc.org/google.golang.org/protobuf/compiler/protogen#GeneratedFile.QualifiedGoIdent) instead of trying to maintain compatibility with identifier naming.

**Comment by skolodyazhnyy** [comment]
Oh it's totally understandable, I just wanted to point out inconsistency. I had to duplicate code generator which is somewhat cumbersome, but works ok.
