### ISSUE TITLE
Unbounded body reads

### ISSUE THREAD

**Issue by cannon73** [twitchtv/twirp#259]
I have some doubts about the T.W.I.R.P. software. The proto buf generator code makes code that uses io.ReadAll to read body data from the network, but io.ReadAll does an unbounded read of how ever much data the other end sends. If you are using T.W.I.R.P. without a proxy in front, would that not be a problem? Kindly include my solution to check the Content-Length against a size limit and to use io.ReadFull and io.ReadAtLeast to limit the size to the Content-Length.

[readall.zip](https://github.com/twitchtv/twirp/files/5064834/readall.zip)

**Comment by spenczar** [comment]
Twirp is designed to be modular and work well with HTTP middleware. You can use the standard library's [`http.MaxBytesReader`](https://golang.org/pkg/net/http/#MaxBytesReader) to limit incoming request bodies. For example, here is some generic middleware - it works with any handler, not just Twirp:

```go
// limit incoming HTTP Request bodies to a maximum size in bytes
func withMaxBytes(h http.Handler, max int64) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		r.Body = http.MaxBytesReader(w, r.Body, max)
		h.ServeHTTP(w, r)
	})
}
```

You could apply it like this:

```go
server := example.NewHaberdasherServer(&randomHaberdasher{}, nil)
handler := withMaxBytes(server, 10*1024*1024)
log.Fatal(http.ListenAndServe(":8080", handler))
```

The reason to prefer this is that it keeps Twirp's code small and focused, and it permits the user to configure their own desired byte limit. It's hard to know what the right byte limit is - some Twirp services have _very_ large request bodies which can be trusted because they only run on an internal network and with service-to-service authentication.
