### ISSUE TITLE
Should The Constant Version Be Bumped to 8?

### ISSUE THREAD

**Issue by marwan-at-work** [twitchtv/twirp#309]
Now that v8 is released, shouldn't [this constant](https://github.com/twitchtv/twirp/blob/fc964007b6a7badaa284114f13ebe08ce821354a/version_constant.go#L19) be also updated to ensure that generated code and library code are compatible? 

Thanks!

**Comment by marioizquierdo** [comment]
No, it should not be updated because the twirp runtime library was not updated; v7 and v8 are the same. The major version release is for the generator. See the new doc we added with a version compatibility matrix: https://twitchtv.github.io/twirp/docs/version_matrix.html

But, to your point, we should probably update the comment on that constant. Thanks for reporting!

**Comment by marwan-at-work** [comment]
ah, love that matrix. thanks!
