### ISSUE TITLE
clientOpts.ReadOpt undefined (type twirp.ClientOptions has no field or method ReadOpt)

### ISSUE THREAD

**Issue by AvivM96** [twitchtv/twirp#324]
Hey,

First of all I love twirp and thanks for all the hard work it is really appreciated !

I've noticed a change that happened a few days ago, an addition to `protoc-gen-twirp`. I'm generating golang protobuf client using `protoc-gen-twirp` but suddenly the build is failing dues to those error messages - 
```
clientOpts.ReadOpt undefined (type twirp.ClientOptions has no field or method ReadOpt)
serverOpts.ReadOpt undefined (type *twirp.ServerOptions has no field or method ReadOpt)
```

In my golang protos client I'm using the latest twirp package - `github.com/twitchtv/twirp v8.0.0+incompatible`
When I'm checking the lib I do see that `ReadOpt` method is missing from `client_options.go`.

what am I doing wrong ?

**Comment by marioizquierdo** [comment]
Sorry for the confusion! There are a few commits on master that have not been released yet. It seems that you are using the right package version for the runtime library, but the `protoc-gen-twirp` code generator must be pulling from master, instead of `v8.0.0`.

Try installing the generator with an explicit version like this:
```go
go get github.com/twitchtv/twirp/protoc-gen-twirp@v8.0.0
```

More info: https://twitchtv.github.io/twirp/docs/install.html

**Comment by AvivM96** [comment]
@marioizquierdo great fixed it :) thanks a lot
