### ISSUE TITLE
Attempting to import import "google/protobuf/descriptor.proto"; yields import errors

### ISSUE THREAD

**Issue by polds** [twitchtv/twirp#37]
This is a copy pasta from #15:

When attempting to import descriptor.proto I run into a Go import issue on the compiled Go.
"google/protobuf/descriptor.proto";

Reproducible:
```Protobuf
syntax = "proto3";
import "google/protobuf/descriptor.proto";
package twitch.twirp.example;
option go_package = "example";

extend google.protobuf.MessageOptions {
    string some_key = 1000;
}

message Hat {
  option (some_key) = "a hat!"
  int32 size = 1;
  string color = 2;
  string name = 3;
}

message Size {
  int32 inches = 1;
}

service Haberdasher {
  rpc MakeHat(Size) returns (Hat);
}
```

Yields the following Go imports:
```Golang
import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "google/protobuf"
```

Which obviously yields the error:
`cannot find package "google/protobuf"`

I verified that importing something like `google/protobuf/timestamp.proto` **does** work correctly, it's just the descriptor.proto that doesn't.

**Comment by spenczar** [comment]
Here's what's happening:

When `protoc` resolves your import declarations, it gathers the right `.proto` files, including `descriptor.proto`. A _good_ version of that file would include the line

```protobuf
option go_package = "github.com/golang/protobuf/protoc-gen-go/descriptor;descriptor";
```

But the version of `google/protobuf/descriptor.proto` that your `protoc` is gathering is missing that line, so `protoc-gen-go` is receiving a version without a go package override.

The most likely way that this can happen is with an old `protoc` installation. `protoc` will check for the file in `/usr/local/include/google/protobuf/descriptor.proto` if it doesn't find it in any other `--proto-path`.  This is hardcoded. If that file is an old version, it might be missing the package line, and this is what you'd get.

Try re-installing protoc, especially being careful to set up `/usr/local/include` correctly.

I'm sorry you're running into this - `protoc` is a thorny tool. I'm going to close this issue just because it isn't in Twirp's power to fix this frustration, but I'm certainly dreaming of a day when `protoc` will be easier to use, or when a viable alternative will be on the scene. I think the right issue to follow along with might be https://github.com/golang/protobuf/issues/222.
