### ISSUE TITLE
Response bodies are not read to EOF in certain cases, potentially causing TCP issues.

### ISSUE THREAD

**Issue by QueenCitySmitty** [twitchtv/twirp#384]
Per the [Golang docs](https://cs.opensource.google/go/go/+/refs/tags/go1.21.0:src/net/http/client.go;l=563-566):

> If the Body is not both read to EOF and closed, the Client's underlying RoundTripper (typically Transport) may not be able to re-use a persistent TCP connection to the server for a subsequent "keep-alive" request.

Both [doProtobufRequest](https://github.com/twitchtv/twirp/blob/206451d552e13701fa1111430aa81235029cb329/protoc-gen-twirp/generator.go#L795) and [doJSONRequest](https://github.com/twitchtv/twirp/blob/main/protoc-gen-twirp/generator.go#L847) only defer closing the body, not also reading to EOF. This has the potential to cause issues with TCP.

Current implementation:

```go
	t.P(`  resp, err := client.Do(req)`)
	t.P(`  if err != nil {`)
	t.P(`    return ctx, wrapInternal(err, "failed to do request")`)
	t.P(`  }`)
	t.P()
	t.P(`  defer func() {`)
	t.P(`    cerr := resp.Body.Close()`)
	t.P(`    if err == nil && cerr != nil {`)
	t.P(`      err = wrapInternal(cerr, "failed to close response body")`)
	t.P(`    }`)
	t.P(`  }()`)
```

Proposed solution:

```go
	t.P(`  resp, err := client.Do(req)`)
	t.P()
	t.P(`  if resp != nil {`)
	t.P(`    defer func() {`)
	t.P(`      io.ReadAll(resp.Body)`)
	t.P(`      cerr := resp.Body.Close()`)
	t.P(`      if err == nil && cerr != nil {`)
	t.P(`        err = wrapInternal(cerr, "failed to close response body")`)
	t.P(`    }()`)
	t.P(`  }`)
	t.P()
	t.P(`  if err != nil {`)
	t.P(`    return ctx, wrapInternal(err, "failed to do request")`)
	t.P(`  }`)
```

**Comment by marioizquierdo** [comment]
This makes sense, thanks!

It seems this issue only manifests if the underlying transport is trying to re-use persistent TPC connections, and for some reason Twirp was not able to read the response body all the way to EOF (calls to `io.ReadAll` (doProtobufRequest) or `json.NewDecoder(resp.Body).Decode` (doJSONRequest)).

Looking at [the client example code](https://github.com/twitchtv/twirp/blob/206451d552e13701fa1111430aa81235029cb329/example/service.twirp.go#L994-L1009), this could happen if the context is canceled.

Instead of always trying to do `io.ReadAll` again, we could only try to do it on `ctx.Err()`. This will be safer to implement, and will not cause a second read on the response body for regular successful requests.

Current implementation:

```go
	t.P(`  if err = ctx.Err(); err != nil {`)
	t.P(`    return ctx, wrapInternal(err, "aborted because context was done")`)
	t.P(`  }`)
```

Proposed solution:

```go
	t.P(`  if err = ctx.Err(); err != nil {`)
	t.P(`    if resp.Body != nil {`)
	t.P(`      _, _ = io.ReadAll(resp.Body) // make sure the response body is fully read`)
	t.P(`    }`)
	t.P(`    return ctx, wrapInternal(err, "aborted because context was done")`)
	t.P(`  }`)
```
