### ISSUE TITLE
Vendor directory is not committed, so protoc-gen-twirp does not build reliably.

### ISSUE THREAD

**Issue by gaffo** [twitchtv/twirp#59]
https://github.com/twitchtv/twirp/blob/4492f81f75b4d504a2eadbda05055f416c076858/Gopkg.toml#L2

Mentions that these deps are only needed for testing. This is however, untrue. They are also needed to build the generators.

**Comment by spenczar** [comment]
Right, you need modern-enough versions of our deps to build `protoc-gen-twirp` so we should probably commit the `vendor` directory. This came up in #57.

We didn't do that at first because vendoring can cause headaches for importers of your library: they must _also_ vendor or else your types are different and packages don't really work together.

I think that doesn't affect twirp, though, since the main library, `github.com/twitchtv/twirp`, has no external dependencies. Nobody will get bitten by this.

We should commit the vendor directory.

**Comment by gaffo** [comment]
And really no one will be importing twirp as the library stands right now
so it shouldn't be an issue. They will just be using the generators.

**Comment by spenczar** [comment]
@gaffo Well, the generated code imports the Twirp library, so I hope _all_ our users import it, or else they are using Twirp in a _really_ weird way. Doesn't make any difference here, though. 😀

**Comment by gaffo** [comment]
Aah ok I was thinking everything was self contained in the generated code.
Would make it easier to have different twirp client versions in the same
system

**Comment by spenczar** [comment]
The shared library is defined to provide types that can be shared across generated packages. You couldn't have `ServerHooks` or `Error` or the context accessors if we put everything in the generated code, so it would be too hard to write libraries to do things like metrics and logging.

As long as the types don't change, it's still easy to have different twirp client versions. We treat changes to those types as a really, really big deal, as a result. It's kind of apocalyptic for users.

**Comment by gaffo** [comment]
Sounds good +1
