### ISSUE TITLE
Allow error msg configuration

### ISSUE THREAD

**Issue by markphelps** [twitchtv/twirp#69]
I may be thinking about using `twirp.Error` the wrong way and if so please ignore me ;).

I noticed that `twirp.Error()` always returns a string in the form `twirp error <Type>: <Msg>` per the docs: https://godoc.org/github.com/twitchtv/twirp#Error

Example from a cli using a generated JSON client:
```
2018/01/28 15:24:57 twirp error already_exists: entity must be unique
```

It would be nice if I could somehow configure the format of this error message to not include `twirp error`. This seems somewhat related to #55 in that the name `twirp` may throw some people off or you may want to 'hide' implementation details (twirp).

I realize that we can always check for `twirp.Error`s and then provide our own error message like what is shown in your docs:
```
if err != nil {
    if twerr := err.(twirp.Error) {
        switch twerr.Code() {
        case twirp.InvalidArgument:
            log.Error("invalid argument "+twirp.Meta("argument"))
        default:
            log.Error(twerr.Error())
        }
    }
}
```

But it may be helpful to not have to do this every time if you just want to print out the error message without `twirp error <Type>:` being prepended.

**Comment by rhysh** [comment]
If you need to remove "twirp" from your logs, you could convert the errors that the generated code returns to use the Error string you prefer.

I don't understand your need completely. Can you explain more? The routing format issue is about how the requests appear on the wire and how they're handled by middleware; do Error strings play a similar role in your applications, or are they seen by users of your software who aren't familiar with the implementation?

You could call a function like this after each Twirp call, before even checking if err is nil:

```
func untwirpify(err error) error {
  if twerr, ok := err.(twirp.Error); ok {
    return fmt.Errorf("%s: %s", twerr.Code(), twerr.Msg())
    // or your own twirp.Error type with a different Error method implementation
  }
  return err // (includes the case where err is nil)
}
```

**Comment by markphelps** [comment]
It's not critical to my application no, it was just unexpected. Other libraries I have used do not namespace the error messages. The simple fact that the error **is** a `twirp.Error` allows me to make the decision if I want to expose the implementation when I log/return my own error messages.

I do realize that I can 'untwirpify' as I stated in the initial issue, but my question is why should I have to? What benefit does `twirp error: ` in the message add that I can't figure out from the fact that it is an implementation of a `twirp.Error`? What if every library you used in your application prepended their own namespace to your error messages and you used something like [errors.Wrap](https://godoc.org/github.com/pkg/errors#Wrap)? `http error: twirp error: github error: actual error message`

My argument is that twirp as a framework/library should not make this decision for me. This is why I referenced issue #55. Not because of how requests appear on the wire but because of these points which I think also apply to error messages (if they are exposed without untwirpifying):

```
* Trademarks: some very large organizations don't want to take any legal risks and are concerned that "twirp" could become trademarked.
* Feels like advertising: This was mentioned in #48: putting "twirp" in all your routes (or error messages) feels like it's just supposed to pump Twirp's brand.
* Homophonous with "twerp": In some Very Serious settings (like government websites), it's not okay that "twirp" sounds like "twerp", which means something like "insignificant pest."
```

Again I may be using twirp incorrectly in returning/logging error messages without first unwrapping them. I just thought I would raise the issue as it was unexpected behavior.

**Comment by spenczar** [comment]
Hi @markphelps - thank you for making an issue! Even if we decide not to make changes, it's always useful to hear if something is unexpected.

First, why we do it this way:

We're not trying to 'namespace' the error here. Instead, it's to try to list the error's code in a helpful way. We could just do `<code>: <msg>`, but it seemed clearer to explain where the code came from. Saying `"unimplemented: MakeHat isn't implemented"` looks kinda stupid and redundant - it doesn't make it clear why we're saying `unimplemented`. So, the idea of `"twirp error <code>"` is to explain the code more clearly, to say "This is Twirp Error Code `unimplemented`".

This has benefits when debugging. It points you in the right direction of the error to understand that something happened in a call a client made. 

---

Second, on whether this is unusual: 

You asked "what if everything looked like `http error: twirp error: github error: actual error message`?" This is a good example, because `net/http` actually does this too 😄 :

- [`errors.New("net/http: use last response")`](https://github.com/golang/go/blob/5af1e7d78e7678db93f12fecc9f0454f7fa2eba9/src/net/http/client.go#L405)
- [`errors.New("http: no Client.Transport or DefaultTransport")`](https://github.com/golang/go/blob/5af1e7d78e7678db93f12fecc9f0454f7fa2eba9/src/net/http/client.go#L209)
- [`errors.New("http: server gave HTTP response to HTTPS client")`](https://github.com/golang/go/blob/5af1e7d78e7678db93f12fecc9f0454f7fa2eba9/src/net/http/client.go#L263)

This was just a few examples out of many, but you get the idea - this is used all over the place in `net/http`. The same can be found elsewhere:
 - `archive/tar` uses "`errors.New("tar: invalid tar header")`)"
 - `bufio` uses "`errors.New("bufio: buffer full")`")
 - `time` uses "`errors.New("time: invalid duration " + orig)"`

and you'll find it in `plugin`, `net/rpc`, `compress/gzip`, `image/gif`, and so on - it's everywhere in the standard library.

That's enough places in the standard library for me to be not too worried here about breaking expectations. I think it's a reasonable enough pattern that users should kinda expect it.

---

Third, what you can do:

`twirp.Error()` does make the decision for you to include the error code in the message. But the `twirp.Error` type also has a `func Msg() string` which does what you want - it just prints the error message without prepending with `twirp error <code>`.

You might say "But I want this to be `twirp.Error`'s output. Well, it seems equally plausible that someone would want it the other direction. Twirp has to pick _some_ direction to go here.

---

Finally, my plans: I don't think I want to change the way Twirp does this. I think it's got a sane justification, is common in the standard library, and there's a reasonable workaround if you really hate it.

If you have additional concerns or if any of this doesn't make sense, please keep commenting on this issue.

**Comment by marioizquierdo** [comment]
I agree for the most part it is better to prefix errors with their type, because that's really the only reliable "stacktrace" that can be used in Go. If an error is wrapped and looks like `"http error: twirp error internal: github error: actual error message"`, then you know at some point in the "stack" it went through a Twirp error.

But it is true that the prefix can be confusing. For example, someone writing a service implementation could see an error like this:

```
twirp error internal: failed to do request: Post http://localhost:8080/twirp/my.package.MyService/MyMethod: dial tcp [::1]:8080: connect: resource temporarily unavailable
```

This error has nothing to do with Twirp, it is an issue with tcp connections in your OS. However the "twirp" prefix may be misleading the developer to think this is a problem with the Twirp framework. This happens because every non-twirp error returned by a Twirp service is wrapped as a Twirp `Internal` error.
