### ISSUE TITLE
Generated clients should set Accept header to right Content-Type

### ISSUE THREAD

**Issue by wolfeidau** [twitchtv/twirp#81]
I am road testing twirp with amazon api gateway and lambda, this service requires the `Accept` header as this triggers binary encoding of the response for `application/protobuf`.

I am happy to do a PR for this.

**Comment by mocax** [comment]
I agree.

**Comment by spenczar** [comment]
I can get behind this, sure. I think there are two design questions though:

1. Errors are always `application/json` responses, even if the client sent a `application/protobuf` request. Should protobuf clients set `Accept: application/protobuf; application/json` to say they are prepared to handle JSON error responses?

I'm not totally sure here. I think I need to know more about how intermediaries like Amazon API Gateway would handle this Accept header, and more about how they'd handle passing through an `application/json` error message if that wasn't in the client's `Accept` set. 

2. Should this be in the spec?

I think no, it shouldn't. We can add it to the Go implementation because it makes things easier for people, and the Twirp spec doesn't forbid additional headers, but it's not actually required by Twirp for any processing, so we should keep things minimal.

@wolfeidau, in your testing, are you able to get JSON-encoded errors back when you set `Accept`  to just `application/protobuf`?

**Comment by wolfeidau** [comment]
Great writeup, I decided to go for a walk to consider this.

1. I think it should be clear to the server what the client accepts, so either `application/protobuf` or `application/json`. This is what I have observed with REST services, even if they specify XML/JSON they may receive any junk in the HTTP errors. 

2. Yeah it is good to be explicit, this helps services like AWS Gateway and various proxy ect understand what your sending through. If I was to add it to a spec it would be _recommended_ not _must_.

In my testing with API Gateway the return data can be either protobuf or JSON / HTML errors when the accept is supplied.

**Comment by spenczar** [comment]
I'm convinced. I've merged your fix into a `v5.3.0_prerelease` branch; I'd like to include #76 in the same release. Once that lands, your fix will make it into master.

**Comment by wolfeidau** [comment]
As mentioned would it be worth adding this to the v6 specification as well?

**Comment by rynop** [comment]
@wolfeidau I'm using APIG Lambda proxy integration and Twirp v6 and APIG keeps returning a bas64 encoded string for an `application/protobuf` response.

- I have `application/protobuf` setup as a `binary media types` in APIG
- My client (javascript) is sending following headers in the `POST`:
   ```
   Accept: application/protobuf 
   Content-Type: application/protobuf
   ```
- Twirp is responding with `content-type: application/protobuf` but the response payload is a bas64 encoded string.

How'd you get around this?  I swear I had this working a few months ago when I 1st tried this.
