### ISSUE TITLE
Add server hook for Prometheus metrics

### ISSUE THREAD

**Issue by joneskoo** [twitchtv/twirp#87]
Currently twirp ships with statsd server hook. I would like to use Prometheus for my metrics.

Are contributions for other server hooks welcome in twirp repository or should they be separate projects?

I adapted the current statsd hook for Prometheus: https://github.com/joneskoo/twirp-serverhook-prometheus . I had to copy some internal stuff for tests, which either suggests to me they should be exported or that this hook should go to twirp repository. Turns out the prometheus client is much simpler than statsd due to labels being easier to work with.

Depending on response I can send a PR.

**Comment by achille-roussel** [comment]
@joneskoo what kind of metrics such handler would provide that differ from the default http handler that the Prometheus Go package already has?

**Comment by joneskoo** [comment]
@achille-roussel Mainly I'm new to both twirp and prometheus so I didn't realize it exist.

There is one difference though. The label "method" is the twirp method, not HTTP method like with [promhttp](https://godoc.org/github.com/prometheus/client_golang/prometheus/promhttp#InstrumentHandlerCounter). The example curries the handler label to the counter, but if the InstrumentHandler sits outside the twirp handler, it's not possible to get the twirp method as a label as far as I can tell.

Is there a way to get the method outside the twirp handler (before routing)? It should be limited to valid twirp methods though, as otherwise one could spam the metrics with non-existing method labels.

Would it make sense to extract this method validation part from ServeHTTP twirp generates to an exported function?

**Comment by spenczar** [comment]
I don't use Prometheus at all, so I can't really evaluate the quality of the hooks. This does sound like a good idea, but I don't think it should go in this repo, just because I wouldn't be a very competent maintainer of them.

I think a separate repo sounds better. I think we should have a list of maintained third-party hook libraries in the Twirp documentation, maybe in the docs on hooks.

@joneskoo, please feel free to make a PR changing `docs/hooks.md` to add a section pointing people towards your hook. Thanks!
