### ISSUE TITLE
Remove HTTPClient, TwirpServer from generated files

### ISSUE THREAD

**Issue by tobiaskohlbau** [twitchtv/twirp#96]
Each generated twirp service for go gets it's own definition of `HTTPClient` and `TwirpServer` see: https://github.com/twitchtv/twirp/blob/df9edc88b8f808cd4c5e83622564f34e0c8a44bf/protoc-gen-twirp/generator.go#L313

This raises issues with storing multiple "different" `TwirpServer` instances for e.g. within an array. I would suggest moving this parts into twirp itself which removes repetition and unifies the handling.

If welcome I'm willing to put together a PR.

**Comment by spenczar** [comment]
Two things: first, I don't understand what issues this raises. Since they are interfaces, and not concrete types, they are mutually assignable. Second, I think it's important not to put this in `github.com/twitchtv/twirp`. 

---
On the first thing:

Could you say more about what code is difficult to write? For example, this works:

```go
var servers []haberdasher.TwirpServer

func init() {
  servers = append(servers, haberdasher.NewHaberdasherServer(...))
  // It's legal to add a "different" TwirpServer because it's assignable to haberdasher.TwirpServer
  servers = append(servers, hellosvc.NewHelloSvcServer(...))
}
```

More simply, you can define an interface locally (and unexported) and use it yourself:
```go

type twirpSrvr interface {
  http.Handler
  ServiceDescriptor() ([]byte, error)
  // don't care about ProtocGenTwirpVersion() string? Fine! Don't include it. No problem.
}

var servers []twirpSrvr

func init() {
  servers = append(servers, haberdasher.NewHaberdasherServer(...))
  servers = append(servers, hellosvc.NewHelloSvcServer(...))
}
```

Go's interface types should make this easy. What's the problem you've hit?

---
On the second:

Things are actually easier because the type is generated in each file. If we want to expand the interface to add a new method to `TwirpServer`, we would have a lot of trouble if it were in the central `github.com/twitchtv/twirp` package. 

Let's say we wanted to add a method, `Name() string`, which returns the service name. Let's also suppose we do what you sugggest - put the `TwirpServer` type definition in `github.com/twitchtv/twirp`. Newly generated code would produce servers which implement `Name() string`, and the `github.com/twitchtv/twirp`'s type would be updated. But _old_ generated code would no longer implement the new interface, and thus wouldn't compile with the new version of `github.com/twitchtv/twirp`.

That matters because it's very common for a project ("A") to provide a Twirp server, but also be a Twirp client of other projects ("B"). In that case, the project would be importing some other project's generated code. If "A" wants to upgrade to the newest Twirp and regenerate, it _can't do so_ until "B" upgrades _first_, because otherwise its imported copy of "B"'s generated code won't compile with the new version of `github.com/twitchtv/twirp`.

This isn't a problem if the generated code includes the interface directly. Then, it's easy to see that things can be upgraded independently.

**Comment by tobiaskohlbau** [comment]
Thanks for your detailed response. I've read your answer multiple times and got your points.
Your first point is totally valid. I didn't know interfaces are mutually assignable. Also the solution with local interface is very neat didn't think of this neither.

I've created the idea cause same Interface definitions within different packages looks a bit cumberstone. Maybe it would be an option to incorporate the type name within the interface to clarify that it's solely for named type and is not meant to be used as generous type (like "grpc" does). `TwirpServer` sounds a bit like it's shared for every service which is generated.

Could be possible to combine both ideas with generating interfaces with type name incorporated and in addition provide a `TwirpServer` interface (within twirp itself) which is more general and satisfies every generated interface which could be used instead of self defined interfaces. See this only as a rough idea.

Your second point is a good catch. Let's hope `vgo` and it's proposal solve this with versioned imports.

I will close this issue as a local interface is the way to go IMHO and I was wrong in first place. Thanks for your time and sorry for bothering you.
